TLP_ENABLE=1
TLP_AUTO_SWITCH=2
TLP_PROFILE_AC=PRF
TLP_PROFILE_BAT=BAL

DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=5

MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=15

CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active

CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=1

NMI_WATCHDOG=0

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave

RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto

USB_AUTOSUSPEND=1
USB_DENYLIST="046d:c52f"
USB_EXCLUDE_AUDIO=1
USB_EXCLUDE_BTUSB=1
USB_EXCLUDE_PHONE=1
USB_EXCLUDE_PRINTER=1
